---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: stage
spec:
  encryptedData:
    password: AgB1TMRRmFBgeeHpqOeeP9YNfBx625zBkmaVDnwtXpSGlehBIw9q9KuViLGO672fVzQglMGgUvrtIrW2g6wYLSXC1o/6Wv6T3t/bVq0BMHA3CU7zfrTGG6c4IF2E1KZ0qUtc1AksxLoExcSZiEN0Br5TQMPVcqRbVb99hljHHvfkmgZW1Gl6k2DMKb4ysNP71LfYufp+GAwjZooqGcMWYdY9xwEuyYzICJ4lsPf4VTQj6iafJ3ANckgeQU5pk0O/ACMR1M834b2SESoiJuMC7KwQahCEKjBRMD9CyTDecitCFUxeNxAwMWjeHO9h9QNzjNpKlS8anQKb8iz+/Se6UCD4kop/B2iapZtR2JYWXX2a1UBlVhyi9sSn5CI88X1GulMCeq4nCyghXSL8KJqLa8cuVRnVwcy+fY6Kns33sKlMptqJSONsFoXmgenfDWOS4XxXrB3aQtN0zac5Vd4UmTL3SaWSwGPMlv2acWAnXP5jm21pnN7wz+ePwZN4eqWaaoQxZ1QAI2mJfGmNF9/O6ZARD3vEpCNeMDDAwr0aIpvm4mpRCtNIeE24VFCmX9J54hHWXYKu0kuYKh3a4lP0l+D4BlBth+VMEE6YyxeSRMyZDATkP7rZkw2Vc8voj/VNXFfqEFKJPKTd5zO4fVlf7tgSXDLUIwA9DOwBA9jclCo2+QbNSp0NdwctaS8ZwKI6cuWUm22RqqGkWHJWdQ==
    username: AgCwIpWlf2eTvkns9odc9wHPiQr+AkqToNSSbUJmB9Zkythksaba2ILoJM/31Y+BXYvWiu1X9tVyx9loM1GU9DJ1aEaQzdDwnSstgYHfXsXFK6A4oELEjVLNKcsgFmdDqxKtmb3zzuZflW/J+Rp2DOjLQv2x1IswR2jrXFCjfneRLkRYdh80t5ahueT5F4GAgg2Aaa8Qzu6PMZVj3S1Oh6pULMqTqa4+TeKV7RFd5pR6iHnNcwCP/TtvSC5CR6H50E2INXQCsccSiQrG6TL3j3KoEDTYbiO8VXIJ0JmD1UO7fdsKJLKfIZ1UW3uMhLzczjwBGsKB0mJSAtFYA69+30JrRC2ATs2r9cZB0+VZg3AHEIrwtGsbXHWOOhkWVyOhhgKTPNYsfnFwtaklnSBJlG5mzO0SN+B07BBM8QsY9Z6LOF4DJrKrAMwR59Myt7PPPTdTimsjFDZ8dWb8JJGeW3y9XQKLSrvQ3RyqyxSmhWRjtcSaH8Oi+cehH2+o9DqVDlEk8V8rz6h4YMAIz6P4kdOeb3pL9mFAUUmnEynj2NQI0jnnhx642gRhrWZLrZSilXpNvrWjGpgfi0Sh3FGKPxVGouQwvQjjE4kyseP+wsnyFOGBscL4KfZe0kTB1vB8RJEIuXE6Yh0MNkGoVO9QSh1XWidhMYH3GjVjhv+vzl+pv1XUAcMglNmdZ9+9N2DXxeerbfQFQg==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: stage
