apiVersion: v1
kind: Service
metadata:
  name: schedule-service-postgres
  namespace: stage
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: schedule-service-postgres