apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage
resources:
  - ../../base/api-gw

patches:
  - target:
      kind: SealedSecret
      name: api-gw-sealed-secret
    path: ./api-gw/sealed-secret.yaml