apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stage-api-gw
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/overlays/stage"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
  targetNamespace: stage