apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pestsov-v/c-argo-infra.git'
    targetRevision: main
    path: k8s/overlays/stage
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true