apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gw-sealed-secret
  namespace: stage
spec:
  encryptedData:
    REDIS_PASSWORD: AgBDV0SJ8r9FXoj6ad/qvntJxGs1ynbefgrjyxnbzMopWe/w0C0QzuCHzqvoy0Trgb+CK/d/DHbbm4poDrJnj+wZbDTDCUhKEUxrs9PgfcZ49JLuaB/agaBVdSatnTlH6CBp619SxhDUsSgsNeJR3FhowjJsTVa4+Aiu3hHGRsmZGjt0NjSD+mT45eO9dW1AM+afj7Dbg+0GJzU/U3KS37JzYGA3O9ggXP6rFwP6aWQTB6tllTuyxQ8uKhtTkQpyVYh9UEAAmm/XiOlGYmmYS9ZVsaqfnmyPEekCZvzQQWIENPsZXWIvuQxPCXcTIcsBB2GpXQo3sA0xEUQodUOAETSVn5Ng0m1nhUbcfwUIjheEojI6ADpQYrMG/SOIXBC+Qa8bkrLEdn6L5pDV1kNNAFhXW68FhGYNsfhwmEs6sHyMX4BF57umEesaqMYdvoRm8Ukr9xluG5/tTtSIMMKRArVNufCl0Gg+ZoqLQmGoibqW2XfQfNawdiyc5TAYfT+x+MBZ9W3unehdb2i3EPBHpUHFkpj8xeioNUeCbiyP3KdAb/w5B7wZ44ndqLfR1PTXdssi1eQmZJJ0rw42CR69Jh1vuh6yih0dgIUjpHsekS+drbK72EYRq0k8ljQY2dFz9c5d+UoeAacBPCXalxhl63872fCbcKXNJV7yeM5IV5VtL5TBoRkpAW2eKtLRJZvpx+JS7iv9wyKBAkCxDg==
    REDIS_USERNAME: AgCvoRqh4ZlpRgmy/K3WTW1sMzY0KScJFVHsqxhKcI9quKYIcW5vugCCKfaYNIiH+2FOm5Wqck/GF2FbL+ywFczITJfQUVuFuACt9mqInu0FTpijz/u57bchek/HupOKUUN5+6NPo+tls8oG1/FvWUYKf9wFm325QK/3KEKvtnbtLPnIogLzdACGHYTYnIIldN9R66sqQOLTx99ZVSQOpatKw0FwQd80mP64KZSuPp+iDZ8I/aetDXywfz6rVyeQo0AVkcqz4EFDK6JDxm51KApWdJmhWka7qjsovZvKg0bEADCyMKpu9cuiNOuHdk9t/Fut90mDiur2HNdCvsAKku0cAtjQLa3Fdn91kmUGoyw00SKd4GP6Z6ccWDuC1NNdlAd18dyYYqoZAnItgQeCfPfD8YYM7oh0AmmjTrVZzPPMg1o1+i7ysohghkHMmJxIA6kaNHgGTieD85x1GH9fHHZ42Zi70giRtA3bFIqDHYMFNiREiIkNcdf9BzjwBTM8Nwqtkhk7wCdr0/F+uhb6Mc0oELVwTq1MZazGvZ5wUN65VYUfihRX/sk75ABQEN7LuBVPcz0yaTiaPHLvWBIwuFWfrFeorSMLnoUT1KCr1BXgS2XhdaSHbBmPjRRftWOCN78bKJU++Dn1RXknHIQ2s5HibGBeBRWYxsOjye2KYMX2wmH+2tYTmHX5jm8wrO1bHSrpB253p05CqBqiVw==
  template:
    metadata:
      creationTimestamp: null
      name: api-gw-sealed-secret
      namespace: stage
