resources:
  - schedule-deployment.yaml
  - schedule-service.yaml

  - redis-deployment.yaml
  - redis-service.yaml

  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml

  - configmap.yaml
  - sealed-secret.yaml